import type { Metadata } from "next";
import { Comfortaa as AppFont } from "next/font/google";
import "./globals.css";
import Header from "./ui/layout/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const appFont = AppFont({
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async defer></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      <body
        className={`${appFont.className} antialiased min-h-screen flex flex-col`}
      >
        <div className="">
          <Header/>
        </div>
        <div className="app-content text-base flex flex-1 flex-col justify-start p-6 md:px-[25vw]">
          {children}
        </div>
      </body>
    </html>
  );
}
